# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
np?

#### 3. Create a null vector of size 10 (★☆☆)

In [19]:
vector_null=np.zeros(10,dtype=np.int8)
vector_null

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

#### 4. How to find the memory size of any array (★☆☆)

In [13]:
np.size(vector_null)

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [14]:
np.size?

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [20]:
vector_nul=np.zeros(10)
vector_nul[4]=1
vector_nul

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [22]:
array_value=np.arange(10,50)
array_value

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [30]:
a=np.array([2,4,5,65,8,5,4,2,8,4])
np.flip(a)

array([ 4,  8,  2,  4,  5,  8, 65,  5,  4,  2])

In [31]:
np.roll(a,-1)

array([ 4,  5, 65,  8,  5,  4,  2,  8,  4,  2])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [28]:
matrice3=np.arange(9).reshape(3,3)
matrice3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [35]:
np.where(np.array([1,2,0,0,4,0])!=0)

(array([0, 1, 4], dtype=int64),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [42]:
identity_matrix=np.zeros((3,3),dtype=np.int8)
for i in range(3):
    identity_matrix[i,i]=1
identity_matrix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [51]:
mat3_3_3=np.random.randint(3,40,(3,3,3))
mat3_3_3

array([[[19, 35, 39],
        [24, 23, 24],
        [16, 12, 25]],

       [[30,  3,  7],
        [24, 37, 19],
        [32,  6, 14]],

       [[ 7, 23,  8],
        [39, 34, 10],
        [16, 31, 37]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [54]:
array2=np.random.randint(0,10,(10,10))
np.min(array2)

0

In [55]:
np.max(array2)

9

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [56]:
np.mean(np.random.randint(0,40,30))

20.4

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [66]:
matt=np.zeros((10,10))
matt[:,-1]=1
matt[:,0]=1
matt[0,:]=1
matt[-1,:]=1
matt

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [69]:
new_array=np.zeros((matt.shape[0]+2,matt.shape[1]+2))
new_array[1:-1,1:-1]=matt
new_array

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [70]:
0 * np.nan

nan

In [71]:
np.nan == np.nan

False

In [72]:
np.inf > np.nan

False

In [73]:
np.nan - np.nan

nan

In [74]:
np.nan in set([np.nan])

True

In [75]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [80]:
identity_matrix=np.zeros((5,5),dtype=np.int8)
for i in range(5):
    identity_matrix[i,i-1]=i
identity_matrix

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]], dtype=int8)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [89]:
scacchiera=np.zeros((8,8),dtype=np.int8)
scacchiera

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [92]:
scacchiera[::2,::2]=1
scacchiera[1::2,1::2]=1
scacchiera


array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]], dtype=int8)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [96]:
np.unravel_index(99,(6,7,8))

(1, 5, 3)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [3]:
np.tile( np.array([[0,1],[1,0]]), (4,4))
#La funzione np.tile() in NumPy viene utilizzata per creare una nuova matrice o array ripetendo 
#una matrice o un array esistente in modo specifico. Nel tuo caso, np.tile(np.array([[0,1],[1,0]]), (4,4)) 
#crea una nuova matrice 2D ottenuta ripetendo la matrice [[0, 1], [1, 0]] in un modello 4x4.

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [6]:

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

'''
Il risultato è che la matrice Z è normalizzata in modo tale che abbia una media zero 
(il valore medio di tutti gli elementi è zero) e una deviazione standard uno 
(la dispersione dei dati è standardizzata a uno). Questa normalizzazione è utile quando 
si desidera mettere a confronto dati provenienti da distribuzioni diverse o quando si 
lavora con algoritmi che richiedono che i dati abbiano una determinata scala.

In breve, normalizzare significa ridurre i dati in modo che abbiano una scala comune e siano 
più facilmente confrontabili o utilizzabili in analisi statistiche.'''

[[-1.43216397  1.462427   -0.32351009 -1.05447488 -0.7547663 ]
 [ 1.54699353  1.43421659  0.28351747  0.52665899  0.02591695]
 [-1.30396026  0.58939711  0.75198321  1.22846839 -1.41235995]
 [-1.2877431   0.11302522  0.70907106  0.60854339 -0.33880568]
 [-1.22733524 -1.04621031  1.52317809  0.09200741 -0.71407461]]


'\nIl risultato è che la matrice Z è normalizzata in modo tale che abbia una media zero \n(il valore medio di tutti gli elementi è zero) e una deviazione standard uno \n(la dispersione dei dati è standardizzata a uno). Questa normalizzazione è utile quando \nsi desidera mettere a confronto dati provenienti da distribuzioni diverse o quando si \nlavora con algoritmi che richiedono che i dati abbiano una determinata scala.\n\nIn breve, normalizzare significa ridurre i dati in modo che abbiano una scala comune e siano \npiù facilmente confrontabili o utilizzabili in analisi statistiche.'

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [7]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [11]:
'''
Il risultato di np.dot(np.ones((5,3)), np.ones((3,2)) sarà una matrice 5x2 ottenuta moltiplicando le due matrici. 
In pratica, ogni elemento della matrice risultante è la somma dei prodotti degli elementi corrispondenti delle 
righe della prima matrice con le colonne della seconda matrice.

Il risultato sarà una matrice 5x2 con tutti gli elementi pari a 3, poiché ciascuna delle 10 posizioni è il prodotto 
di una riga della prima matrice per una colonna della seconda matrice, entrambe contenenti solo il valore 1. 
Quindi, ogni elemento nella matrice risultante è 1 * 1 + 1 * 1 + 1 * 1 = 3.'''
np.dot(np.ones((5,3)), np.ones((3,2)))

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
a=np.random.randint(0,15,20)
a[(a>=3)&(a<9)]=-1
a

array([ 9, 14, -1,  1, 10,  1,  0,  2, -1, -1, -1, 10,  9,  0, 13, -1,  0,
        9,  2,  0])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [20]:
'''
print(sum(range(5), -1)):

range(5) crea una sequenza di numeri da 0 a 4, cioè [0, 1, 2, 3, 4].
sum(range(5), -1) calcola la somma degli elementi nella sequenza range(5) utilizzando la funzione sum(). 
Il secondo argomento -1 specifica l'asse lungo cui sommare. In questo caso, -1 indica di sommare lungo 
l'ultimo asse, quindi il risultato sarà la somma degli elementi della sequenza, che è 10.
from numpy import * importa tutte le funzioni di NumPy nel namespace corrente.

print(sum(range(5), -1)):

Qui, sum() si riferisce alla funzione sum() di NumPy, in quanto abbiamo importato tutte le funzioni di NumPy.
sum(range(5), -1) utilizza la funzione sum() di NumPy per calcolare la somma degli elementi nella sequenza 
range(5) lungo l'asse specificato, che è l'ultimo asse. In questo caso, il risultato sarà un array NumPy [10], 
che è diverso dal risultato precedente.
'''
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [21]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z

C:\Users\pelle\AppData\Local\Temp\ipykernel_21256\803206331.py:1: RuntimeWarning: invalid value encountered in power
  Z**Z


TypeError: ufunc 'left_shift' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [22]:
np.array(0) / np.array(0)

C:\Users\pelle\AppData\Local\Temp\ipykernel_21256\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [23]:
np.array(0) // np.array(0)

C:\Users\pelle\AppData\Local\Temp\ipykernel_21256\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [24]:
np.array([np.nan]).astype(int).astype(float)

C:\Users\pelle\AppData\Local\Temp\ipykernel_21256\699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-2.14748365e+09])

#### 29. How to round away from zero a float array ? (★☆☆)

In [26]:
'''
np.random.uniform(-10, +10, 10): Crea un array NumPy di 10 elementi contenenti valori casuali uniformemente 
distribuiti nell'intervallo da -10 (incluso) a +10 (escluso).

np.abs(Z): Calcola il valore assoluto di ciascun elemento nell'array Z, rendendo tutti i valori positivi.

np.ceil(np.abs(Z)): Applica la funzione ceil() (soffitto) per arrotondare ciascun valore assoluto all'intero 
successivo o uguale.

np.copysign(np.ceil(np.abs(Z)), Z): Applica copysign() per assegnare il segno originale di ciascun elemento 
arrotondato all'array risultante. In altre parole, conserva il segno originale dei valori casuali.
'''
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[  1.   2.  -5.  10.  -4.   3.   9. -10.   3.  10.]


#### 30. How to find common values between two arrays? (★☆☆)

In [27]:
'''
np.intersect1d(Z1, Z2): Utilizza la funzione intersect1d() di NumPy per trovare l'intersezione (elementi comuni) 
tra i due array Z1 e Z2.

Il risultato stampato con print() sarà un array NumPy che contiene tutti gli elementi che sono comuni sia a Z1 che a Z2. 
Gli elementi comuni saranno elencati una sola volta nell'array risultante, anche se compaiono più volte in uno o 
entrambi gli array originali.
'''
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 2 4 6 7]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [ ]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [28]:
'''
np.sqrt(-1) utilizza la funzione di radice quadrata standard di NumPy e restituirà un valore nan 
(Not-a-Number) perché NumPy non gestisce automaticamente i numeri complessi in questo caso.

np.emath.sqrt(-1) utilizza la gestione dei numeri complessi fornita da NumPy e restituirà un valore complesso 1j, 
che rappresenta l'unità immaginaria.
'''
np.sqrt(-1) == np.emath.sqrt(-1)


C:\Users\pelle\AppData\Local\Temp\ipykernel_21256\244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [29]:
valori=np.random.randint(0,60,80)
ieri=np.roll(valori,1)
domani=np.roll(valori,-1)

In [34]:
np.datetime64('today') - np.timedelta64(1)

numpy.datetime64('2023-11-04')

In [35]:
np.datetime64('today')

numpy.datetime64('2023-11-05')

In [36]:
np.datetime64('today') + np.timedelta64(1)

numpy.datetime64('2023-11-06')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [38]:
#out definisce in che array viene salvato il risultato
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [40]:
Z = np.random.uniform(0,10,10)
print(Z)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[9.48286677 1.37256437 7.5620998  4.73324837 4.33390227 9.15120828
 2.44763817 9.38703681 8.32470989 9.71798252]
[9. 1. 7. 4. 4. 9. 2. 9. 8. 9.]
[9. 1. 7. 4. 4. 9. 2. 9. 8. 9.]
[9. 1. 7. 4. 4. 9. 2. 9. 8. 9.]
[9 1 7 4 4 9 2 9 8 9]
[9. 1. 7. 4. 4. 9. 2. 9. 8. 9.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [42]:
np.random.randint(0,5,(5,5))

array([[4, 4, 0, 3, 1],
       [0, 0, 4, 0, 3],
       [4, 0, 1, 2, 3],
       [4, 4, 1, 2, 4],
       [0, 2, 4, 3, 3]])

In [43]:
#sommo ogni elemento con il suoa rispettivo nell'altro array
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [46]:
def arrayGenerator():
    lista=[]
    for i in range(11):
        lista.append(i)
    return lista
print(np.array(arrayGenerator()))

[ 0  1  2  3  4  5  6  7  8  9 10]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [47]:
np.random.uniform(0,1,10)

array([0.33165365, 0.95094158, 0.9480801 , 0.7562433 , 0.67437361,
       0.719627  , 0.9028784 , 0.61463592, 0.15286687, 0.8890218 ])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [48]:
np.sort(np.random.randint(0,90,6))

array([ 0, 20, 31, 42, 43, 88])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [49]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [52]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
A==B

array([False,  True,  True,  True,  True])

In [53]:
np.array_equal(A,B)

False

#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)