## tempo di esecuzione
%%timeit-> comando magico, mi da il tempo di esecuzione

la deviazione standard mi dice quanto i voti sono vicini alla media

se ho tutti 7 avrò 0

timeit lo esegue più volte, poi fa la media e la deviazione standard

con i comandi magici tutte le variabili diventano locali


In [1]:
#%%timeit
#per sapere quanto ci mette a eseguire il codice
quadrati=[]
for i in range(1,10000):
    quadrati.append(i**2)

In [2]:
quadrati

[1,
 4,
 9,
 16,
 25,
 36,
 49,
 64,
 81,
 100,
 121,
 144,
 169,
 196,
 225,
 256,
 289,
 324,
 361,
 400,
 441,
 484,
 529,
 576,
 625,
 676,
 729,
 784,
 841,
 900,
 961,
 1024,
 1089,
 1156,
 1225,
 1296,
 1369,
 1444,
 1521,
 1600,
 1681,
 1764,
 1849,
 1936,
 2025,
 2116,
 2209,
 2304,
 2401,
 2500,
 2601,
 2704,
 2809,
 2916,
 3025,
 3136,
 3249,
 3364,
 3481,
 3600,
 3721,
 3844,
 3969,
 4096,
 4225,
 4356,
 4489,
 4624,
 4761,
 4900,
 5041,
 5184,
 5329,
 5476,
 5625,
 5776,
 5929,
 6084,
 6241,
 6400,
 6561,
 6724,
 6889,
 7056,
 7225,
 7396,
 7569,
 7744,
 7921,
 8100,
 8281,
 8464,
 8649,
 8836,
 9025,
 9216,
 9409,
 9604,
 9801,
 10000,
 10201,
 10404,
 10609,
 10816,
 11025,
 11236,
 11449,
 11664,
 11881,
 12100,
 12321,
 12544,
 12769,
 12996,
 13225,
 13456,
 13689,
 13924,
 14161,
 14400,
 14641,
 14884,
 15129,
 15376,
 15625,
 15876,
 16129,
 16384,
 16641,
 16900,
 17161,
 17424,
 17689,
 17956,
 18225,
 18496,
 18769,
 19044,
 19321,
 19600,
 19881,
 20164,
 20449

## INTRODUZIONE A NUMPY
numpy non è un modulo nativo, anaconda contiene numpy

- si basa sugli array (ndarray)

gli array in python non esistono, esistono le liste


In [2]:
import numpy as np
#costrutto aias, io nel codice lo richiamo con np, aias standard

### creazione array a 1 dimensione

In [4]:
#array di zeri
#è un oggetto di numpy
#sono float
array_di_zeri= np.zeros(10)
array_di_zeri

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
#questo attributo mi dice il tipo della variabile
array_di_zeri.dtype

dtype('float64')

In [6]:
#per creare un array di interi, int 8-> interi a 8 bit
array_di_zeri_int=np.zeros(10,dtype=np.int8)
array_di_zeri_int

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [7]:
array_di_zeri_int.dtype

dtype('int8')

In [8]:
array_di_uni=np.ones(5)
array_di_uni

array([1., 1., 1., 1., 1.])

In [9]:
#esiste solo zero e one, si utilizza numpy-> moltiplico per 3
array_di_tre=np.ones(5)*3#-> broadcast
#se moltiplico un array numpy per un numero, la moltiplicazine viene fatta elemento per elemento, come fosse un ciclo for
array_di_tre

array([3., 3., 3., 3., 3.])

In [10]:
array_num_crescenti=np.arange(1,10)#-> posso creare un array di interi crescenti
array_num_crescenti

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
array_num_crescenti.dtype

dtype('int32')

In [12]:
%%timeit
array_quadrati=np.arange(1,10000)**2 #->broadcast
#questo è molto più veloce

38.5 µs ± 3.26 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [47]:
array_quadrati=np.arange(1,10000)**2 #->broadcast
#questo è molto più veloce

In [48]:
array_quadrati

array([       1,        4,        9, ..., 99940009, 99960004, 99980001])

numpy è molto veloce, a livello del c

### casuale vs pseudo-casuale

casuale: es la moneta

pseudo-casuale: un algoritmo simula il casuale

random.org-> la casualità dipende dal rumore atmosferico, è realmente casuale

In [ ]:
#array pseudo-casuali di numeri interi
np.random.randint(1,101,10)

In [ ]:
#array pseudo-casuali di numeri float
np.random.uniform(0,5,10)#-> ogni numero ha la stessa probabilità di uscire

## curva gaussiana
la curva gaussiana è definita da due numeri: 

    - il valor medio
    - la relazioen standard
    
    
## distribuzione gaussiana

In [3]:
#array pseudo-casuali di numeri float gaussiani
np.random.normal(180,5,20)

array([177.28275394, 175.07641748, 178.70651504, 179.37399133,
       175.21694613, 183.25198573, 181.36371355, 175.24312066,
       180.33904883, 179.35687337, 176.05299313, 175.93440573,
       180.99843587, 184.12389689, 176.32937346, 180.12324979,
       186.33598979, 184.3084477 , 184.23529786, 184.47924798])

i testi, le parole, la popolazione non è distribuita in maniera gaussiana

#### esercizio:
Alice e bob fanno una partita a dadi, ognuno lancia un dado 10 volte.
- Calcolare quante volte alice fa un punteggio maggiore di bob.
- Scrivere i punteggi ottenuti da alice quando ha vinto    

In [ ]:
np.random.seed(123)#seme del generatore di numeri casuali, se abbiamo tutti lo stesso seme abbiamo gli stessi numeri
alice=np.random.randint(1,7,10)
bob=np.random.randint(1,7,10)
print(f"lanci di alice: {alice}, lanci di bob: {bob}")
      

In [ ]:
alice_vince=alice>bob#-> se maggiore da true

In [ ]:
alice_vince.dtype

In [ ]:
print(f"alice vince : {np.count_nonzero(alice_vince)}")#-> count non zero conta i true

In [ ]:
#+ sintetico
np.count_nonzero(alice>bob)

In [ ]:
alice[alice>bob] #-> di chiama INDICIZZAZIONE BOOLEANA

### Esercizio:
Simula 20 voti tra 2 e 10 generandoli in maniera pseudo-casuale.

- conta quante sono le suffiecienze
- scrivi le insuffiecienze


In [ ]:
np.random.seed(123)
voti=np.random.randint(2,11,20)

In [ ]:
voti

In [ ]:
print(f"i voti sufficienti sono: {np.count_nonzero(voti[voti>=6])}, i voti isufficienti sono: {voti[voti<6]}")

In [ ]:
#np.random.choice(["testa","croce"])
np.random.choice(["testa","croce"],15)
#dtype-> <U5 -> stringhe unicode, permette di codificare emoticon, caratterri ecc
#il numero indica il numero di caratteri

creare un array 1d a partire da una lista python

In [18]:
array=np.array([1,2,3,4,5])#-> gli do una lista e mi crea l'array, capisce da solo il tipo
array

array([1, 2, 3, 4, 5])

In [19]:
array.dtype

dtype('int32')

In [23]:
array=np.array([1,2,"A","ciao"])
array

array(['1', '2', 'A', 'ciao'], dtype='<U11')

In [25]:
array.dtype#tutti gli elementi dello stesso tpo, obbligato a creare delle stringhe

dtype('<U11')

un'immagine a scala di grigi è un array bidimensionale

un'immagine a colori è un array a tre dimensioni

un film è un array a 4 dimensioni

### array a più di una dimensione


In [14]:
matrice=[[1,2,3],[4,5,6]]
matrice

[[1, 2, 3], [4, 5, 6]]

In [26]:
array2d=np.array(matrice)
array2d
#-> creo un array bidimensionale

array([[1, 2, 3],
       [4, 5, 6]])

##### shape
la shape dell'array1d è 5-> 5 elementi
- i 5 elementi dell'array si sviluppano da sinistra a destra, il primo numero è quello con indice 0
- 1 sola dimensione-> dimensione 0 e abbiamo 5 elementi lungo la dimensione 0
- qui la dimensione 0 è quella orizzontale

nell'array2d la shape mi da 2-> righe, 3-> colonne
- in 1 array bidimensionale ho 2 direzioni
- lungo la direzione 0 ho 2 righe
- lungo la direzione 1 ho 3 colonne
- la dimensione 0 sono le righe-> verticale
- la dimensione 1 sono le colonne-> orizzontale

le matrici hanno senso di esistere se sono di forma rettangolare

In [27]:
array2d.shape#attributo degli array

(2, 3)

In [31]:
array1d=np.arange(0,5)
array1d

array([0, 1, 2, 3, 4])

In [30]:
array1d.shape

(5,)

### creazione di array >2

In [33]:
matrice0=np.zeros((10,5))
matrice0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
matrice0.shape#-> mi restituisce l'argomento della funzione np.zeros

(10, 5)

##### array tridimensionale
pila di matrici, nella stampa risulta sballato, ogni matrice ha 2 righe, 3 colonne
- la dimensione 0 corre su 4 possibilità
- la dimensione 1 mi da le righe-> 2
- la dimensione 2 mi da le colonne-> 3

In [36]:
matrice0_1=np.zeros((4,2,3))
matrice0_1

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
matrice0_1.shape

(4, 2, 3)

In [38]:
matrice0_1=np.zeros((2,4,3))
matrice0_1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [46]:
matrice=np.random.randint(1,7,(5,5))
matrice
#-> tutti questi metodi mi danno una matrice se gli do una tupla al posto che una dimensione

array([[1, 1, 5, 2, 2],
       [5, 1, 3, 1, 4],
       [3, 3, 6, 2, 1],
       [1, 6, 1, 5, 4],
       [1, 3, 1, 4, 3]])

### flatten
mi permette di passare da array nd ad array 1d
- mette ogni riga in coda alla precedente

In [66]:
vettore=matrice.flatten()#mi trasforma la matrice in un array 1d, mette ogni riga in cosa, in ordine dall'alto al basso

In [67]:
vettore

array([1, 1, 5, 2, 2, 5, 1, 3, 1, 4, 3, 3, 6, 2, 1, 1, 6, 1, 5, 4, 1, 3,
       1, 4, 3])

In [68]:
#gli passo le dimensioni della matrice, DEVONO ESSERE GIUSTE, se gli do -1: (5,-1), si calcola lui le colonne
vettore.reshape((5,5))

array([[1, 1, 5, 2, 2],
       [5, 1, 3, 1, 4],
       [3, 3, 6, 2, 1],
       [1, 6, 1, 5, 4],
       [1, 3, 1, 4, 3]])

In [69]:
#gli passo le dimensioni della matrice, DEVONO ESSERE GIUSTE, se gli do -1: (5,-1), si calcola lui le colonne
vettore.reshape((5,-1))

array([[1, 1, 5, 2, 2],
       [5, 1, 3, 1, 4],
       [3, 3, 6, 2, 1],
       [1, 6, 1, 5, 4],
       [1, 3, 1, 4, 3]])

In [70]:
vettore1=np.random.uniform(0,1,57)
vettore1

array([0.2527369 , 0.28100633, 0.47911097, 0.0052125 , 0.3033033 ,
       0.89647985, 0.99502433, 0.99137503, 0.04731412, 0.49199747,
       0.7118822 , 0.67380308, 0.34612921, 0.06655511, 0.4387617 ,
       0.13602602, 0.92089131, 0.85494733, 0.8208931 , 0.12794777,
       0.55909367, 0.31941947, 0.12980866, 0.27960779, 0.55551284,
       0.90862359, 0.13724781, 0.343053  , 0.61765619, 0.4825378 ,
       0.43608567, 0.34055395, 0.54129186, 0.04026331, 0.31526355,
       0.34664159, 0.27502606, 0.6204971 , 0.30216349, 0.32024123,
       0.92479992, 0.58533238, 0.37623798, 0.83729011, 0.72943945,
       0.09537967, 0.65618684, 0.96584297, 0.06991185, 0.09105864,
       0.88643038, 0.22113835, 0.39273887, 0.53188241, 0.14436904,
       0.22825387, 0.18434704])

In [71]:
matrice0_4=vettore1.reshape((3,-1))

In [72]:
matrice0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [74]:
vettore5=np.arange(1,10)
vettore5

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#### roll
shifta l'array avanti o indietro

In [75]:
np.roll(vettore5,-1)

array([2, 3, 4, 5, 6, 7, 8, 9, 1])

In [76]:
np.roll(vettore5,+1)

array([9, 1, 2, 3, 4, 5, 6, 7, 8])

In [77]:
np.roll(vettore5,+3)

array([7, 8, 9, 1, 2, 3, 4, 5, 6])

#### esercizio
dato n costruire un array 2d come il seguente [[1,2,3.....n-1][1,2,3.....n-1]....[1,2,3.....n-1]] con n righe

In [85]:
n=5
np.arange(0,n)

array([0, 1, 2, 3, 4])

In [87]:
np.arange(0,n*n)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [90]:
n=5
matrice6=(np.arange(0,n*n)%n).reshape((n,-1))
matrice6

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int32)

In [92]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.arange(0,10)%3

array([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype=int32)

In [94]:
np.roll(matrice6,-1)#roll sulle colonne

array([[1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0]], dtype=int32)

In [97]:
#axis definisce la dimensione su cui operare
np.roll(matrice6,-1,axis=1)#roll sulle righe

array([[1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0],
       [1, 2, 3, 4, 0]], dtype=int32)

### esercizio: il prezzo di un'azione
simuliamo il prezzo di un'azione di un azienda

np.random.normal(1,5,200)
- 1 - valor medio, ogni giorno aumenta di 1
- 5 - deviazione standard

genero le variazioni di prezzo di tutti i giorni e le sommo, calcolo solo la variazione

In [101]:
prezzo=100+np.cumsum(np.random.normal(1,5,200))
prezzo

array([111.43984361, 114.82215012, 112.97642921, 110.90894389,
       106.46995331, 112.23478864, 119.6119074 , 117.60741519,
       117.84827035, 122.72040853, 118.27492672, 120.13041036,
       124.10688831, 120.84744441, 118.15840142, 117.95695133,
       117.52849907, 119.13792067, 113.93583159, 111.77530534,
       108.07015485, 110.66645122, 105.23851565, 102.36725254,
       107.66981906, 108.08894674, 104.40329422, 106.49178072,
       102.25986676,  94.78573419,  95.11923416,  88.75461514,
        90.53863641,  86.77041988,  89.00512298,  89.09949142,
        99.66266199, 107.25033199, 114.56435507, 111.13773593,
       112.78121984, 111.27630107, 113.31418153, 114.36256945,
       125.23229899, 121.88398484, 125.02657414, 128.22208849,
       138.1997972 , 143.03289934, 137.34805034, 143.6682928 ,
       146.77460541, 152.25194248, 150.4311432 , 155.51476438,
       144.84215994, 146.84494042, 150.45859879, 154.27729627,
       162.94216556, 163.70805419, 164.66065929, 161.28

## somma comulativa
nel primo copia il primo,
nel secondo la somma dei primi 2
nel terzo la somma dei primi 3

In [103]:
np.cumsum([1,1,1,1,1,1])

array([1, 2, 3, 4, 5, 6])