In [ ]:
type(a)#mi da il tipo della variabile inserita

In [1]:
import numpy as np

In [2]:
Z=np.arange(1,15)
r=[]

for i in range(len(Z)):
    if i<(Z[-1]-3):
        r.append(Z[i:(i+4)])   
R=np.array(r)
R = R.reshape(-1,4)
print(R)  




R0=np.array([Z[i:(i+4)] for i in range(len(Z)-3)])
R0

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

## LETTURA FILE

In [ ]:
file=open(filePath,"r",encoding="utf-8")
#righe=file.readlines()
caratteri=file.read()
file.close()

In [ ]:
" ".join(righe_senza_return)#mette la l'insieme di liste da unire

## LIST COMPRENSION

In [ ]:
quadrati_perfetti=[i**2 for i in range(1,10)]

In [ ]:
parole_c= [parola for parola in parole if parola[0]=="c"]

In [ ]:
#python-style ciclo for su entrambe le liste
#zip prende le tue liste e le fa scorrere in parallelo, si ferma alla lung più breve se di lung diverse
for elemento, elemento2 in zip(lista,lista2):
    print(f"{elemento}   -  {elemento2}")

In [ ]:
#python-style con enumerate, come se scorressi gli indici
for indice, elemento in enumerate(lista):
    print(f"in posizione {indice} troviamo l'elemento {elemento}")

## DIZIONARIO

In [ ]:
for chiave, valore in d.items():
    print(f"la chiave è {chiave} e il valore è {valore}")

In [ ]:
d = {"a":["albero","albergo"],"b":["bello"],"c":["ciao","cellulare"]}
d[f]="napoli"

## FUNZIONI NUMPY

In [2]:
import numpy as np

In [ ]:
np.where(condizione)#mi ritorna la tupla degli indici di dove viene soddi

In [ ]:
array_di_zeri= np.zeros(10)#crea un array con solo 0,(10,dtype=np.int8) setto il tipo

In [ ]:
array_di_uni=np.ones(5)#crea un array di soli 1

In [ ]:
#esiste solo zero e one, si utilizza numpy-> moltiplico per 3
array_di_tre=np.ones(5)*3#-> broadcast
#se moltiplico un array numpy per un numero, la moltiplicazine viene fatta elemento per elemento, come fosse un ciclo for

In [ ]:
array_num_crescenti=np.arange(1,10)#-> posso creare un array di interi crescenti

In [ ]:
#array pseudo-casuali di numeri interi
np.random.randint(1,101,10)

In [ ]:
#array pseudo-casuali di numeri float
np.random.uniform(0,5,10)#-> ogni numero ha la stessa probabilità di uscire

In [ ]:
#array pseudo-casuali di numeri float gaussiani
np.random.normal(180,5,20)

In [ ]:
np.random.seed(123)#seme del generatore di numeri casuali, se abbiamo tutti lo stesso seme abbiamo gli stessi numeri

In [ ]:
np.random.choice(["testa","croce"],15)



gio_1=np.random.choice([1,2,3,4,5,6],(num_partite,num_lanci),p=[1/8,1/8,1/8,1/8,1/4,1/4])
#creo una matrice dove setto le probailità di uscita delle varie componenti della lista


errore_t1=np.random.choice([True, False], (num_minuti,3),p=[0.001,0.999])

In [ ]:
p.count_nonzero(voti[voti>=6])#conta quante volte non è 0, False...

In [ ]:
matrice.flatten()

In [ ]:
array2d.shape#attributo degli array
#mi ristiruisce una tupla con nuemero di righe, numero di colonne

In [ ]:
#gli passo le dimensioni della matrice, DEVONO ESSERE GIUSTE, se gli do -1: (5,-1), si calcola lui le colonne
vettore.reshape((5,-1))#numero righe, num colonne

In [ ]:
np.roll(vettore5,-1)

In [ ]:
prezzo=100+np.cumsum(np.random.normal(0,10,10))#valor medio, deviazione standard e numero di dati

deviazione_standard=np.std(prezzo)

In [ ]:
np.cumsum([1,1,1,1,1,1])#somma i numeri, ogni numero è uguale alla somma di tutti i precendenti

In [ ]:
array1d=np.linspace(-5,5,11)#usa numeri float equispaziati, così ne prendo 11 nell'intervallo -5,5

In [ ]:
sin_1=np.sin(2*np.pi*frequenza_1*arrayFloat)
#la uso per calcolare la sinusoinde, np.pi è il pgreco

In [ ]:
np.tile( np.array([[0,1],[1,0]]), (4,4))
#La funzione np.tile() in NumPy viene utilizzata per creare una nuova matrice o array ripetendo 
#una matrice o un array esistente in modo specifico. Nel tuo caso, np.tile(np.array([[0,1],[1,0]]), (4,4)) 
#crea una nuova matrice 2D ottenuta ripetendo la matrice [[0, 1], [1, 0]] in un modello 4x4.

In [ ]:
np.abs(Z)# Calcola il valore assoluto di ciascun elemento nell'array Z, rendendo tutti i valori positivi.

np.ceil(np.abs(Z))# Applica la funzione ceil() (soffitto) per arrotondare ciascun valore assoluto all'intero 
#successivo o uguale.
np.copysign(np.ceil(np.abs(Z)), Z)# Applica copysign() per assegnare il segno originale di ciascun elemento 
#arrotondato all'array risultante. In altre parole, conserva il segno originale dei valori casuali.

In [ ]:
'''
np.intersect1d(Z1, Z2): Utilizza la funzione intersect1d() di NumPy per trovare l'intersezione (elementi comuni) 
tra i due array Z1 e Z2.

Il risultato stampato con print() sarà un array NumPy che contiene tutti gli elementi che sono comuni sia a Z1 che a Z2. 
Gli elementi comuni saranno elencati una sola volta nell'array risultante, anche se compaiono più volte in uno o 
entrambi gli array originali.
'''

print(np.intersect1d(Z1,Z2))

In [ ]:
#per ignorare i warning di numpy
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

In [ ]:
'''
np.sqrt(-1) utilizza la funzione di radice quadrata standard di NumPy e restituirà un valore nan 
(Not-a-Number) perché NumPy non gestisce automaticamente i numeri complessi in questo caso.

np.emath.sqrt(-1) utilizza la gestione dei numeri complessi fornita da NumPy e restituirà un valore complesso 1j, 
che rappresenta l'unità immaginaria.
'''
np.sqrt(-1) == np.emath.sqrt(-1)

In [ ]:
# metodi per estrarre la parte intera di un numero
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

In [3]:
#sommo ogni elemento con il suoa rispettivo nell'altro array
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [ ]:
np.array_equal(A,B)

## FUNZIONI PLT

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
plt.plot(prezzo)

In [ ]:
np.max(prezzo):.2f

In [ ]:
np.min(prezzo):.2f

In [ ]:
np.mean(valori)

In [ ]:
plt.imshow(immagine)

In [ ]:
np.max(misure_pulite,axis=0)

#axis 0 colonne, axis uno righe-> da verificare