In [1]:
import numpy as np

#### ESERCIZIO 2
Genera un array di numpy contenente i primi 100 numeri primi.

In [5]:
lista_numP=[]
i=1
num0=0
while len(lista_numP) <101:
    for y in range(1,i+1):
        if i%y==0:
            num0=num0+1
    if num0==2:
        lista_numP.append(i)
    num0=0
    i=i+1
    
    
numPrimi=np.array(lista_numP)
print(numPrimi)

[  2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59  61
  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149 151
 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251
 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359
 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463
 467 479 487 491 499 503 509 521 523 541 547]


#### funzione sympy-> ci sono molte funzioni per il calcolo simbolico

In [1]:
def primo(x):
    if x<2:
        return false;
    for i in range(2,int(x**0.5)+1):
        if x%i==0:
            return False
    return True
numeri_primi=[x for x in range(2,100) if primo(x)][:100]

In [6]:
numeri= np.arange(3,1001)
numeri

array([   3,    4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
         14,   15,   16,   17,   18,   19,   20,   21,   22,   23,   24,
         25,   26,   27,   28,   29,   30,   31,   32,   33,   34,   35,
         36,   37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
         47,   48,   49,   50,   51,   52,   53,   54,   55,   56,   57,
         58,   59,   60,   61,   62,   63,   64,   65,   66,   67,   68,
         69,   70,   71,   72,   73,   74,   75,   76,   77,   78,   79,
         80,   81,   82,   83,   84,   85,   86,   87,   88,   89,   90,
         91,   92,   93,   94,   95,   96,   97,   98,   99,  100,  101,
        102,  103,  104,  105,  106,  107,  108,  109,  110,  111,  112,
        113,  114,  115,  116,  117,  118,  119,  120,  121,  122,  123,
        124,  125,  126,  127,  128,  129,  130,  131,  132,  133,  134,
        135,  136,  137,  138,  139,  140,  141,  142,  143,  144,  145,
        146,  147,  148,  149,  150,  151,  152,  1

In [12]:
numeri=numeri[numeri%2!=0]
numeri

array([  5,   7,  11,  13,  17,  19,  23,  25,  29,  31,  35,  37,  41,
        43,  47,  49,  53,  55,  59,  61,  65,  67,  71,  73,  77,  79,
        83,  85,  89,  91,  95,  97, 101, 103, 107, 109, 113, 115, 119,
       121, 125, 127, 131, 133, 137, 139, 143, 145, 149, 151, 155, 157,
       161, 163, 167, 169, 173, 175, 179, 181, 185, 187, 191, 193, 197,
       199, 203, 205, 209, 211, 215, 217, 221, 223, 227, 229, 233, 235,
       239, 241, 245, 247, 251, 253, 257, 259, 263, 265, 269, 271, 275,
       277, 281, 283, 287, 289, 293, 295, 299, 301, 305, 307, 311, 313,
       317, 319, 323, 325, 329, 331, 335, 337, 341, 343, 347, 349, 353,
       355, 359, 361, 365, 367, 371, 373, 377, 379, 383, 385, 389, 391,
       395, 397, 401, 403, 407, 409, 413, 415, 419, 421, 425, 427, 431,
       433, 437, 439, 443, 445, 449, 451, 455, 457, 461, 463, 467, 469,
       473, 475, 479, 481, 485, 487, 491, 493, 497, 499, 503, 505, 509,
       511, 515, 517, 521, 523, 527, 529, 533, 535, 539, 541, 54

In [4]:
numeri= np.arange(3,1001)
for divisore in range(2,100):
    numeri=numeri[numeri%divisore!=0]
    
numeri

array([101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163,
       167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229, 233,
       239, 241, 251, 257, 263, 269, 271, 277, 281, 283, 293, 307, 311,
       313, 317, 331, 337, 347, 349, 353, 359, 367, 373, 379, 383, 389,
       397, 401, 409, 419, 421, 431, 433, 439, 443, 449, 457, 461, 463,
       467, 479, 487, 491, 499, 503, 509, 521, 523, 541, 547, 557, 563,
       569, 571, 577, 587, 593, 599, 601, 607, 613, 617, 619, 631, 641,
       643, 647, 653, 659, 661, 673, 677, 683, 691, 701, 709, 719, 727,
       733, 739, 743, 751, 757, 761, 769, 773, 787, 797, 809, 811, 821,
       823, 827, 829, 839, 853, 857, 859, 863, 877, 881, 883, 887, 907,
       911, 919, 929, 937, 941, 947, 953, 967, 971, 977, 983, 991, 997])

#### ESERCIZIO 4
Genera un array di numpy contenente i primi 10 numeri della successione di Fibonacci.

In [14]:
lista_fibo=[]
while len(lista_fibo)<10:
    if len(lista_fibo)<2:
        lista_fibo.append(1)
    else: 
        lista_fibo.append(lista_fibo[len(lista_fibo)-1]+lista_fibo[len(lista_fibo)-2])
fibo=np.array(lista_fibo)
for f in fibo:
    print(f)

1
1
2
3
5
8
13
21
34
55


In [17]:
num_fibo=np.zeros(10, dtype=np.int8)
num_fibo[0:2]=1
num_fibo
for i in range(2,10):
    num_fibo[i]=num_fibo[i-1]+num_fibo[i-2]
num_fibo

array([ 1,  1,  2,  3,  5,  8, 13, 21, 34, 55], dtype=int8)

#### ESERCIZIO 5
Considera l'array: Z = [1,2,3,4,5,6,7,8,9,10, 11,12, 13, 14].
Genera un array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6],....
[11,12, 13, 14]].

In [3]:
Z=np.arange(1,15)
r=[]

for i in range(len(Z)):
    if i<(Z[-1]-3):
        r.append(Z[i:(i+4)])   
R=np.array(r)
R = R.reshape(-1,4)
print(R)  


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [4]:
R1=np.split(Z,[0,4, 1,5, 2,6, 3,7, 4,8, 5,9, 6,10, 7,11, 8,12, 9,13, 10,14])
R1

[array([], dtype=int32),
 array([1, 2, 3, 4]),
 array([], dtype=int32),
 array([2, 3, 4, 5]),
 array([], dtype=int32),
 array([3, 4, 5, 6]),
 array([], dtype=int32),
 array([4, 5, 6, 7]),
 array([], dtype=int32),
 array([5, 6, 7, 8]),
 array([], dtype=int32),
 array([6, 7, 8, 9]),
 array([], dtype=int32),
 array([ 7,  8,  9, 10]),
 array([], dtype=int32),
 array([ 8,  9, 10, 11]),
 array([], dtype=int32),
 array([ 9, 10, 11, 12]),
 array([], dtype=int32),
 array([10, 11, 12, 13]),
 array([], dtype=int32),
 array([11, 12, 13, 14]),
 array([], dtype=int32)]

In [11]:
R0=np.array([Z[i:(i+4)] for i in range(len(Z)-3)])
R0

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]])

#### ESERZIO 9

Usa la seguente funzione np.random.normal (mean, dev, shape)
per generare un ndarray che contenga la stima dell'altezza degli alunni della tua classe; I'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in centimetri nel modo più realistico possibile.

In [9]:
np.random.normal(180,5,20)

array([177.41664052, 169.94970612, 178.77328933, 180.7649116 ,
       178.45497761, 178.2522228 , 177.8802436 , 181.28337632,
       180.09828443, 184.15054886, 182.64120272, 179.77704976,
       181.48261136, 185.50526079, 179.11684313, 171.58858711,
       185.89248596, 185.14026658, 183.54489398, 187.69663039])

In [23]:
lista_altezze=np.array([186,181,170,182,182,180,182,182,176,166,175,181,
               188,182,178,170,186,185,183,166])
media_approssimativa=np.mean(lista_altezze)
deviazione_standard=np.std(lista_altezze)
numero_compagni=1200
#len(lista_altezze)
altezza_massima=np.max(lista_altezze)
altezza_minima=np.min(lista_altezze)
print(f"altezza media= {media_approssimativa:.1f}, deviazione standard: {deviazione_standard:.1f}")
altezze_simulate=np.random.normal(media_approssimativa,deviazione_standard,numero_compagni)
altezze_simulate

altezza media= 179.1, deviazione standard: 6.4


array([171.24106788, 173.80630829, 192.68491438, ..., 183.60450465,
       169.42564798, 171.75704718])

In [27]:
np.count_nonzero(altezze_simulate<170)

91

#### ESERCIZIO 10

Usa numpy per creare dei dati simulati riferiti alla seguente situazione (in certi casi i dati simulati sono una buona approssimazione della realtà).
Nel parco vicino alla scuola è installata una centralina per la misurazione del livello di polveri sottili PM10 nell'aria. Talvolta la centralina va in uno stato di errore per cui la misurazione delle PM10 fallisce e il dato corrispondente riporta il valore 9999,9 all'interno dell'array delle misurazioni dati. Crea un array di 1000 campioni che generino dei valori secondo una distribuzione normale con valore medio 19 e varianza 5 e supponi che la centralina sia andata in errore 20 volte. La distribuzione gaussiana è una buona approssimazione dei dati reali della centralina? Motiva la risposta.

In [32]:
dati=np.random.normal(19,5,1000)
valori_da_sostituire= np.random.choice(dati,20,replace=False)
for valore in valori_da_sostituire:
    indice = np.where(dati == valore)
    #print(dati[indice])
    dati[indice]=float(9999.9)
    #print(dati[indice])
    
for dato in dati:
    print(dato)
    
#secondo me si perchè simula le oscillazioni che potrebbero essere simili a quelle reali

21.842361041498222
20.379046961662638
10.710291794247825
9.704877170580938
23.045212166788154
18.613208808479907
20.084098518158687
18.572707636792195
20.189720969847226
13.657069288568115
14.599811301822761
24.375913755676333
17.58793539282252
15.487028664284475
14.968384875314719
12.551084467312588
23.814282357293678
21.127269539285678
17.94386507157856
23.437868055595555
12.545042469982773
14.021985881763527
24.3503590620428
9999.9
21.319214382071088
19.22297086395307
19.69625647787642
16.31907177253536
26.19480172233146
16.565172775572567
13.042535200577625
26.79414898412316
15.742314876154689
21.15050120644513
18.383317851531114
6.797505905487155
17.723904168087103
12.73830733759928
26.183055639180324
18.42829848478847
14.034989240489566
22.68050133908468
22.26489012427576
12.899573865464385
23.994061257004002
24.466397063894473
14.997292516263094
15.756424116868487
27.38212433771999
15.61694368187143
9.035699816841454
14.714633239117942
20.912695574229208
20.344776618279013
21.74

In [38]:
dati=np.random.normal(19,5,1000)
valori_da_sostituire= np.random.choice(1000,20,replace=False)
dati[valori_da_sostituire]=9999.9   
for dato in dati:
    print(dato)


17.14115964084366
33.453467846175755
16.653785995280234
23.494249138361702
11.92732944462603
15.590776801988575
23.822861102281916
21.46729700193217
25.90137036204513
21.889519317631475
21.20266672303639
16.869799761146894
20.756568567489452
21.344501352118407
31.6298466439437
12.219124010536552
24.59927873623309
25.483218033710347
24.23229047594305
15.855296759903906
22.257671084752495
6.168045088489507
7.785939662245394
25.46765218753405
15.219031056075668
27.581618339959743
13.992694287812835
13.42580514116552
8.903974889025463
12.927125348348616
33.11351776628038
17.680823099883412
24.171903999880232
20.261014356109445
16.908257290122073
15.866547691536734
25.23214689786923
11.288843922260488
19.860480248352843
13.944179168946636
17.243576254415252
16.896960172081897
18.435243969732994
21.280600929756517
22.435844724565342
20.09553528403631
24.574673365604802
24.558546722953466
15.808378171478566
22.379722764243454
21.09014171521146
26.228014835895276
19.883620997196093
14.99119641

In [36]:
np.count_nonzero(dati==9999.9)

20