In [3]:
import numpy as np

#### ESERCIZIO 2
Genera un array di numpy contenente i primi 100 numeri primi.

In [5]:
lista_numP=[]
i=1
num0=0
while len(lista_numP) <101:
    for y in range(1,i+1):
        if i%y==0:
            num0=num0+1
    if num0==2:
        lista_numP.append(i)
    num0=0
    i=i+1
    
    
numPrimi=np.array(lista_numP)
print(numPrimi)

[  2   3   5   7  11  13  17  19  23  29  31  37  41  43  47  53  59  61
  67  71  73  79  83  89  97 101 103 107 109 113 127 131 137 139 149 151
 157 163 167 173 179 181 191 193 197 199 211 223 227 229 233 239 241 251
 257 263 269 271 277 281 283 293 307 311 313 317 331 337 347 349 353 359
 367 373 379 383 389 397 401 409 419 421 431 433 439 443 449 457 461 463
 467 479 487 491 499 503 509 521 523 541 547]


#### ESERCIZIO 4
Genera un array di numpy contenente i primi 10 numeri della successione di Fibonacci.

In [17]:
lista_fibo=[]
while len(lista_fibo)<11:
    if len(lista_fibo)<2:
        lista_fibo.append(1)
    else: 
        lista_fibo.append(lista_fibo[len(lista_fibo)-1]+lista_fibo[len(lista_fibo)-2])
fibo=np.array(lista_fibo)
for f in fibo:
    print(f)

1
1
2
3
5
8
13
21
34
55
89


#### ESERCIZIO 5
Considera l'array: Z = [1,2,3,4,5,6,7,8,9,10, 11,12, 13, 14].
Genera un array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6],....
[11,12, 13, 14]].

In [8]:
Z=np.arange(1,15)
r=[]
lungh=4
for i in range(len(Z)):
    if i<(Z[-1]-3):
        r.append(Z[i:(i+4)])
#print(r)   
R=np.array(r)
R = R.reshape(-1,4)
print(R)  


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### ESERZIO 9

Usa la seguente funzione np.random.normal (mean, dev, shape)
per generare un ndarray che contenga la stima dell'altezza degli alunni della tua classe; I'ndarray deve avere lunghezza pari al numero di compagni di classe. I valori mean e dev devono essere stimati in modo tale da simulare la distribuzione dell'altezza degli alunni in centimetri nel modo più realistico possibile.

In [9]:
np.random.normal(180,5,20)

array([177.41664052, 169.94970612, 178.77328933, 180.7649116 ,
       178.45497761, 178.2522228 , 177.8802436 , 181.28337632,
       180.09828443, 184.15054886, 182.64120272, 179.77704976,
       181.48261136, 185.50526079, 179.11684313, 171.58858711,
       185.89248596, 185.14026658, 183.54489398, 187.69663039])

#### ESERCIZIO 10

Usa numpy per creare dei dati simulati riferiti alla seguente situazione (in certi casi i dati simulati sono una buona approssimazione della realtà).
Nel parco vicino alla scuola è installata una centralina per la misurazione del livello di polveri sottili PM10 nell'aria. Talvolta la centralina va in uno stato di errore per cui la misurazione delle PM10 fallisce e il dato corrispondente riporta il valore 9999,9 all'interno dell'array delle misurazioni dati. Crea un array di 1000 campioni che generino dei valori secondo una distribuzione normale con valore medio 19 e varianza 5 e supponi che la centralina sia andata in errore 20 volte. La distribuzione gaussiana è una buona approssimazione dei dati reali della centralina? Motiva la risposta.

In [10]:
dati=np.random.normal(19,5,1000)
valori_da_sostituire= np.random.choice(dati,20, replace=False)
for valore in valori_da_sostituire:
    indice = np.where(dati == valore)
    #print(dati[indice])
    dati[indice]=float(9999.9)
    #print(dati[indice])
    
for dato in dati:
    print(dato)

20.46126641237643
21.336621234813975
17.51775841477116
26.9929212776757
24.348461464846736
20.129850719261462
14.49495951299188
21.93670351629578
18.33057705256641
14.914599162505164
23.5511287010505
11.557834575800289
29.521018252446403
18.95084472784823
27.779333542396806
23.152803397844217
27.614912443874502
21.28633757255283
24.03618733134119
8.619157742947673
25.996452292869108
22.970240932512237
28.575595887139105
28.76052898255339
22.066644805891666
15.210174161857667
16.902877378446874
20.67863849403171
20.658922492303283
17.965028955483604
25.509782600618184
22.054747907105792
16.69098706571809
14.385522401861362
27.346966442527734
8.1646088428028
16.596462923928694
12.278449096694889
18.31554828688999
12.564217657145878
19.673634682224623
19.523703753049446
15.587969140075277
15.23703831729574
18.14396146365447
23.283635165426226
16.519702130155657
7.802451948530141
14.980280626540594
28.66090604102204
21.105210450600183
26.85473978557659
10.930807119237146
5.486915864490445
